name: Deploy Discord Bots

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-bot1:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies for Bot1
      run: |
        cd ECHObot
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the bot1
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN_BOT1 }}
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: |
        cd ECHObot
        python bot.py

  build-and-deploy-bot2:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies for Bot2
      run: |
        cd bot2
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the bot2
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN_BOT2 }}
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: |
        cd bot2
        python bot.py